name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: riversidefm/github-actions/.github/workflows/gitops-ci-node.yml@main
    with:
      node-version: '22.14.0'
      runs-on: '["self-hosted", "k8s", "medium"]'
      env: |
        OTEL_SERVICE_NAME=identifier
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}