name: Build & Push to ECR

on:
  push:
    branches:
      - main
      - master
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  packages: read

jobs:
  build:
    uses: riversidefm/github-actions/.github/workflows/gitops-build.yml@main
    with:
      ecr-repository: seats-manager
    secrets: inherit

  print-image-metadata:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Show image digest and tag
        run: |
          echo "Image Digest: ${{ needs.build.outputs.image_digest }}"
          echo "Image Tag: ${{ needs.build.outputs.image-tag }}"

